# Generated by Django 6.0.3 on 2026-03-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliosite",
            name="snapchat_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="portfoliosite",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
    ]
