# Generated by Django 6.0.3 on 2026-03-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_portfoliosite_snapchat_url_portfoliosite_twitter_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="category",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="project_client",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="project_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="service",
            name="icon",
            field=models.CharField(blank=True, default="camera", max_length=50),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="client_photo_url",
            field=models.URLField(blank=True),
        ),
    ]
