import type { PortfolioPayload } from "@/lib/types";

export const demoPortfolio: PortfolioPayload = {
  id: 0,
  brand_name: "آيد للتصوير الجوي",
  tagline: "تصوير سينمائي بالطائرات المسيّرة للوجهات والمناسبات والعلامات التجارية",
  hero_title: "لقطات جوية بمستوى سينمائي احترافي",
  hero_subtitle:
    "منصة متكاملة لعرض أعمال التصوير الجوي وإدارة المحتوى الإبداعي بتجربة مشاهدة سلسة وفاخرة.",
  about_title: "مصوّر متخصص في المشاهد الجوية والحركة والجمال البصري",
  about_body:
    "المنصة جاهزة لتكون مكتبة حية لأعمالك الجوية. ارفع المقاطع السينمائية، اعرض أجود صورك، انشر الإعلانات، واحتفظ بجميع استفسارات عملائك منظمةً في لوحة تحكم واحدة.",
  services_title: "ما يمكنك حجزه",
  contact_email: "hello@ayed-aerial.test",
  contact_phone: "+966 5X XXX XXXX",
  base_city: "الرياض",
  instagram_url: "",
  youtube_url: "",
  tiktok_url: "",
  whatsapp_url: "",
  twitter_url: "",
  snapchat_url: "",
  meta_title: "",
  meta_description: "",
  services: [
    {
      id: 1,
      title: "حملات العلامات التجارية",
      description: "مشاهد جوية سينمائية لمجالس السياحة والعلامات الفندقية والإطلاقات التجارية الكبرى.",
      short_label: "حملات",
      icon: "globe",
      sort_order: 1,
      is_published: true,
    },
    {
      id: 2,
      title: "أفلام العقارات",
      description: "طيران احترافي فوق المشاريع العقارية وكشف المخططات الرئيسية وسرد بصري محكم للمطورين.",
      short_label: "عقارات",
      icon: "building",
      sort_order: 2,
      is_published: true,
    },
    {
      id: 3,
      title: "تغطية الفعاليات",
      description: "تغطية جوية عالية التأثير للمهرجانات وحفلات الأعراس والفعاليات الوطنية والتجارب الخاصة.",
      short_label: "فعاليات",
      icon: "calendar",
      sort_order: 3,
      is_published: true,
    },
  ],
  images: [],
  videos: [],
  announcements: [
    {
      id: 1,
      badge: "حجوزات مفتوحة",
      title: "جلسات التصوير الجوي لموسم الربيع متاحة الآن للوجهات السياحية والقطاع الفندقي.",
      body: "",
      cta_label: "",
      cta_url: "",
      starts_at: null,
      ends_at: null,
      is_published: true,
    },
  ],
  testimonials: [
    {
      id: 1,
      client_name: "فريق علامة سياحية",
      client_role: "شريك الحملة",
      quote: "اللقطات النهائية كانت راقية وسينمائية وقابلة للاستخدام مباشرةً في محتوى الإطلاق.",
      rating: 5,
      sort_order: 1,
      is_published: true,
    },
    {
      id: 2,
      client_name: "عميل فعالية خاصة",
      client_role: "مناسبة فاخرة",
      quote: "المقاطع الجوية غيّرت تمامًا كيف نتذكر الحفل. الاتساع والحركة كانا استثنائيَيْن.",
      rating: 5,
      sort_order: 2,
      is_published: true,
    },
  ],
};